# Configuración que arranca el ms pero también va a buscar su config a config server

spring.application.name=transacciones-service

# Configuracion Database Oracle (wallet)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${DB_TNS_ADMIN}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Conexion al Config Server
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.username=admin
spring.cloud.config.password=admin

# HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:https.p12
server.ssl.key-store-password=https123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https