spring.application.name=transacciones-service

# HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:https.p12
server.ssl.key-store-password=https123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https