spring.application.name=web-bff

# SSL Bundle para conexiones HTTPS hacia otros microservicios
spring.ssl.bundle.jks.transacciones.truststore.location=classpath:truststore.p12
spring.ssl.bundle.jks.transacciones.truststore.password=trust123
spring.ssl.bundle.jks.transacciones.truststore.type=PKCS12

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:https.p12
server.ssl.key-store-password=https123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https

# Config Server
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.username=admin
spring.cloud.config.password=admin

# Eureka
eureka.client.restclient.enabled=false
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG