# Configuracion Database Oracle (wallet)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${DB_TNS_ADMIN}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Ajustes recomendados HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin@localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.prefer-ip-address=false

# Resilience4j - Retry para publicación de eventos
resilience4j.retry.instances.activemq.maxAttempts=3
resilience4j.retry.instances.activemq.waitDuration=2s

# Resilience4j - Circuit Breaker para ActiveMQ
resilience4j.circuitbreaker.instances.activemq.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.activemq.slidingWindowSize=5
resilience4j.circuitbreaker.instances.activemq.failureRateThreshold=50
resilience4j.circuitbreaker.instances.activemq.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.activemq.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.activemq.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.activemq.automaticTransitionFromOpenToHalfOpenEnabled=true

# ActiveMQ
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://127.0.0.1:61616}
spring.activemq.user=admin
spring.activemq.password=admin