# Da la configuración al microservicio transacciones service

server.port=8081
spring.application.name=transacciones-service

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreaker.enabled=true

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9000/.well-known/jwks.json}
