# Da la configuración al microservicio transacciones service

server.port=8081
spring.application.name=transacciones-service

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreaker.enabled=true
